version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Heroku orbを起動する

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # 事前に設定されたジョブ deploy-via-git を使う
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: cimg/ruby:2.4-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
      - image: cimg/postgres:9.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # インストールの依存関係をバンドル
      - run: bundle install --path vendor/bundle
      # データベースの設定
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake
