version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 

workflows:
    example-workflow:
      jobs:
        - heroku/deploy-via-git:
            api-key: HEROKU_API_KEY
            app-name: tetsunosuke-menta-test 
            branch: main 